import {test,expect,type Page} from '@playwright/test';
import {parsePage} from '../../server/page';
const demoUrl='https://luma.com/aic-jev';
// Synthetic page content keeps UI tests independent of the live event and network.
const demoPage=parsePage('<html><head><title>Test event</title></head><body><main><h1>Test event</h1><p>Event date: January 1, 2030</p><p>Location: Test venue</p><button>Register</button></main></body></html>',demoUrl);
async function mockJev(page:Page,delay=0){await page.route('**/api/rank',async route=>{const {page:p,task}=route.request().postDataJSON();if(delay)await new Promise(r=>setTimeout(r,delay));const results=p.blocks.map((b:{id:string;text:string})=>({id:b.id,category:'CONTENT',score:b.text.includes('Event date:')?3:1,confidence:.9,probabilities:{'0':0,'1':b.text.includes('Event date:')?0:1,'2':0,'3':b.text.includes('Event date:')?1:0},categoryConfidence:.9,priority:b.text.includes('Event date:')?'NOW':'LATER'}));await route.fulfill({json:{snapshotId:p.id,task,model:'TEST-ONLY-MOCK',latencyMs:12,results,request:{testOnly:true},source:'Jev'}});});}
test.beforeEach(async({page})=>{await page.route('**/api/page',route=>{expect(route.request().postDataJSON()).toEqual({url:demoUrl});return route.fulfill({json:demoPage});});await page.goto('/');});
test('loads the Luma URL without fabricated Jev scores',async({page})=>{await page.getByRole('button',{name:'Load Luma event example'}).click();await expect(page.getByLabel('Website URL')).toHaveValue(demoUrl);await expect(page.getByLabel('I want to')).toHaveValue('Find the event date, location, and how to register.');await expect(page.getByText('DOM ORDER · NOT YET CLASSIFIED')).toBeVisible();await expect(page.getByRole('textbox',{name:'Stable reading output'})).toHaveValue('Test event');await page.getByRole('button',{name:'DOM',exact:true}).click();await expect(page.locator('.dom-source')).toContainText('Event date:');await expect(page.locator('.score-bar')).toHaveCount(0);});
test('validated classification updates order, source selection, voice control and Braille output',async({page})=>{await mockJev(page);await page.getByRole('button',{name:'Luma event example',exact:true}).click();await page.getByRole('button',{name:'Classify with Jev'}).click();await expect(page.getByRole('textbox',{name:'Stable reading output'})).toHaveValue(/Event date:/);await expect(page.locator('.block-row').first()).toContainText('3.0');await expect(page.locator('.cell i.up').first()).toBeVisible();await page.getByRole('button',{name:'Next block',exact:true}).click();await expect(page.getByRole('textbox',{name:'Stable reading output'})).not.toHaveValue(/Event date:/);await page.getByRole('button',{name:'Listen',exact:true}).click();await page.getByRole('button',{name:'Reader mode'}).click();await expect(page.getByLabel('Reading block')).toBeVisible();await expect(page.locator('.walkthrough')).not.toBeVisible();});
test('task change invalidates in-flight classification',async({page})=>{await mockJev(page,1200);await page.getByRole('button',{name:'Load Luma event example'}).click();await page.getByRole('button',{name:'Classify with Jev'}).click();await page.getByLabel('I want to').fill('Find the event organizers instead');await expect(page.getByText('DOM ORDER · NOT YET CLASSIFIED')).toBeVisible();await page.waitForTimeout(1500);await expect(page.locator('.score-bar')).toHaveCount(0);});
test('API failure preserves exact reading and never fabricates fallback scores',async({page})=>{await page.route('**/api/rank',r=>r.fulfill({status:503,json:{error:'Live Jev needs an API key.'}}));await page.getByRole('button',{name:'Load Luma event example'}).click();const before=await page.getByRole('textbox',{name:'Stable reading output'}).inputValue();await page.getByRole('button',{name:'Classify with Jev'}).click();await expect(page.getByRole('alert')).toContainText('API key');await expect(page.getByRole('textbox',{name:'Stable reading output'})).toHaveValue(before);await expect(page.locator('.score-bar')).toHaveCount(0);});
test('mobile layout, hardware disclosure and downloadable extension',async({page})=>{await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'About the hardware'}).click();await expect(page.getByRole('dialog')).toContainText('no physical display');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Get the extension'}).click();await expect(page.getByRole('link',{name:'Download the extension ZIP'})).toHaveAttribute('href','/brailly-extension.zip');await page.keyboard.press('Escape');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
