import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parseHTML} from 'linkedom';
import {extractDocument,readingOrder} from '../shared/dom';
import {parsePage,publicAddress,fetchPublicHtml} from '../server/page';
import {createDomRequest,validateDomResponse} from '../server/dom-jev';
const fixture='<html><head><title>Museum</title></head><body><nav><a href="/visit">Visit</a></nav><main><h1>Visit us</h1><p>Open 10 am–6 pm.</p><button aria-label="Buy tickets">Buy</button><p hidden>secret</p><div aria-hidden="true"><p>hidden parent</p></div><input type="password" value="password-secret"><input name="email" value="private-email"><p><a href="/book">Book admission</a></p><script>alert(1)</script></main></body></html>';
function page(){const {document}=parseHTML(fixture);return extractDocument(document as unknown as Document,'https://example.com/');}
function response(p=page()){const answers:Record<string,unknown>={};for(const b of p.blocks){answers[`score_${b.id}`]={type:'score',score:b.text.includes('10 am')?3:1,confidence:.9,legend:{'0':'Irrelevant','1':'Background','2':'Useful','3':'Essential'},probabilities:b.text.includes('10 am')?{'0':0,'1':0,'2':0,'3':1}:{'0':0,'1':1,'2':0,'3':0}};answers[`kind_${b.id}`]={type:'choice',choice:'CONTENT',confidence:.9,probabilities:{CONTENT:1,ACTION:0,NAVIGATION:0,NOTICE:0,EXTRA:0}};}return {model:'test-model',answers};}
test('extracts actual semantic DOM, excludes hidden content and form values',()=>{const p=page();assert.equal(p.title,'Museum');assert.ok(p.blocks.some(b=>b.text==='Open 10 am–6 pm.'));assert.ok(p.blocks.some(b=>b.text==='Buy tickets'));assert.ok(p.blocks.some(b=>b.region==='nav'));assert.equal(p.blocks.filter(b=>b.text==='Book admission').length,1);assert.ok(!JSON.stringify(p).includes('secret'));assert.ok(!JSON.stringify(p).includes('private-email'));assert.ok(!p.blocks.some(b=>b.text==='alert(1)'));});
test('bounds page input and declares truncation',()=>{const {document}=parseHTML('<html><body>'+Array.from({length:90},(_,i)=>`<p>Paragraph ${i}</p>`).join('')+'</body></html>');const p=extractDocument(document as unknown as Document,'https://example.com');assert.equal(p.blocks.length,60);assert.equal(p.totalCandidates,90);assert.equal(p.truncated,true);});
test('preview strips scripts, event handlers, forms, navigation and unsafe URLs',()=>{const p=parsePage(fixture+'<img src="javascript:alert(1)" onerror="alert(1)"><iframe src="https://evil.test"></iframe>','https://example.com');assert.ok(!p.previewHtml!.includes('<script'));assert.ok(!p.previewHtml!.includes('<iframe'));assert.ok(!p.previewHtml!.includes('onerror'));assert.ok(!p.previewHtml!.includes('javascript:'));assert.ok(!p.previewHtml!.includes('password-secret'));assert.ok(p.previewHtml!.includes("script-src 'none'"));});
test('rejects private and special network targets',async()=>{for(const ip of ['127.0.0.1','10.0.0.1','172.16.0.1','192.168.0.1','169.254.169.254','0.0.0.0','::1','::ffff:127.0.0.1','fc00::1','fe80::1','100.64.0.1'])assert.equal(publicAddress(ip),false,ip);assert.equal(publicAddress('93.184.216.34'),true);await assert.rejects(fetchPublicHtml('http://127.0.0.1/'));await assert.rejects(fetchPublicHtml('file:///etc/passwd'));});
test('one structured Score and Choice per DOM block, using exact source',()=>{const p=page();const request=createDomRequest(p,'Find opening hours','jev');assert.equal(Object.keys(request.questions).length,p.blocks.length*2);assert.deepEqual(request.state.dom_blocks,p.blocks);const q=request.questions.score_b1 as {type:string;instructions:unknown;criteria:unknown[]};assert.equal(q.type,'score');assert.equal(typeof q.instructions,'object');assert.equal(q.criteria.length,4);});
test('valid model scores sort exact source text, all original blocks remain available',()=>{const p=page();const r=validateDomResponse(response(p),p,'Find hours',{},100);const ordered=readingOrder(p,r);assert.equal(ordered[0].text,'Open 10 am–6 pm.');assert.equal(ordered.length,p.blocks.length);assert.equal(r.source,'Jev');assert.deepEqual(readingOrder({...p,id:'new'},r),p.blocks);});
test('missing answer or mathematically inconsistent score rejects entire result',()=>{const p=page();const raw=response(p);delete raw.answers.score_b1;assert.throws(()=>validateDomResponse(raw,p,'task',{},100));const raw2=response(p);(raw2.answers.score_b1 as {score:number}).score=3;assert.throws(()=>validateDomResponse(raw2,p,'task',{},100));});
test('keeps article prose and prioritizes content after long navigation menus',()=>{const {document}=parseHTML('<html><body><nav>'+Array.from({length:80},(_,i)=>`<a href="/nav/${i}">Navigation ${i}</a>`).join('')+'</nav><main><h1>Article heading</h1><p>Read the <a href="/guide">complete guide</a> before visiting.</p>'+Array.from({length:70},(_,i)=>`<p>Article paragraph ${i}</p>`).join('')+'</main></body></html>');const p=extractDocument(document as unknown as Document,'https://example.com');assert.equal(p.blocks.length,60);assert.ok(p.blocks.some(b=>b.text==='Read the complete guide before visiting.'));assert.ok(p.blocks.some(b=>b.text==='Article heading'));assert.equal(p.blocks.filter(b=>b.region==='main').length,48);assert.equal(p.totalCandidates,153);assert.ok(p.blocks.every((b,i)=>i===0||b.order>p.blocks[i-1].order));});
test('resolves base URLs for links, images, and embedded CSS while preserving keyboard links',()=>{const p=parsePage('<html><head><base href="https://cdn.example.com/articles/"><style>.cover{background:url(../cover.png)}</style></head><body><main><p>Article</p><a href="next">Next article</a><img data-src="photo.jpg"><div style="background-image:url(./texture.png)"></div></main></body></html>','https://example.com/news');assert.equal(p.blocks.find(b=>b.text==='Next article')?.href,'https://cdn.example.com/articles/next');const {document}=parseHTML(p.previewHtml!);assert.equal(document.querySelector('a')?.getAttribute('data-brailly-href'),'https://cdn.example.com/articles/next');assert.equal(document.querySelector('a')?.getAttribute('href'),'#');assert.equal(document.querySelector('img')?.getAttribute('src'),'https://cdn.example.com/articles/photo.jpg');assert.ok(document.querySelector('style')?.textContent.includes('https://cdn.example.com/cover.png'));assert.ok(document.querySelector('div')?.getAttribute('style')?.includes('https://cdn.example.com/articles/texture.png'));assert.equal(document.querySelector('base'),null);});
test('stable IDs survive source mutations with a bounded result',()=>{const {document}=parseHTML('<html><body><main><p>Opening hours</p><p>Entrance</p></main></body></html>');const before=extractDocument(document as unknown as Document,'https://example.com');document.querySelector('p')!.textContent='New opening hours';const after=extractDocument(document as unknown as Document,'https://example.com');assert.equal(after.blocks[0].id,before.blocks[0].id);assert.equal(after.blocks[1].id,before.blocks[1].id);assert.notEqual(after.id,before.id);});
test('explicit selection includes a later article block without increasing the request budget',()=>{const {document}=parseHTML('<html><body><main>'+Array.from({length:90},(_,i)=>`<p>Paragraph ${i}</p>`).join('')+'</main></body></html>');extractDocument(document as unknown as Document,'https://example.com');const id=document.querySelectorAll('p')[89].getAttribute('data-brailly-id')!;const p=extractDocument(document as unknown as Document,'https://example.com',false,id);assert.equal(p.blocks.length,60);assert.equal(p.blocks.find(b=>b.id===id)?.text,'Paragraph 89');});
test('embedded styles and hidden child text are excluded from readable prose',()=>{const p=parsePage('<html><body><main><p>Braille <style>.dots{color:red}</style>is tactile.<span hidden>secret note</span></p></main></body></html>','https://example.com');assert.equal(p.blocks[0].text,'Braille is tactile.');});
