import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowLeft,ArrowUpRight,AudioLines,Check,ChevronDown,Code2,Download,Globe,Headphones,Layers,LoaderCircle,MousePointer2,PanelRight,Play,RefreshCw,Search,Settings2,ShieldCheck,Volume2,VolumeX,X} from 'lucide-react';
import {extractDocument,readingOrder,type PageSnapshot,type Classification,type DomBlock} from '../shared/dom';
import {toBraille} from './braille';
const extension=typeof chrome!=='undefined'&&!!chrome.runtime?.id;
const API=extension?'https://brailly-jev.vercel.app':'';
const categoryLabel={CONTENT:'Content',ACTION:'Action',NAVIGATION:'Navigation',NOTICE:'Notice',EXTRA:'Extra'};
const priorityLabel={NOW:'Read first',NEXT:'Read next',LATER:'Later',REVIEW:'Uncertain'};
export default function App(){
 const [page,setPage]=useState<PageSnapshot|null>(null);const [url,setUrl]=useState('');const [task,setTask]=useState('Find the opening hours, ticket price, and accessible entrance.');const [result,setResult]=useState<Classification|null>(null);
 const [busy,setBusy]=useState<'load'|'rank'|null>(null);const [error,setError]=useState('');const [status,setStatus]=useState('Choose a web page to get started.');const [configured,setConfigured]=useState(false);const [selected,setSelected]=useState('');const [offset,setOffset]=useState(0);const [cellOffset,setCellOffset]=useState(0);const [cells,setCells]=useState(40);const [showCode,setShowCode]=useState(false);const [modal,setModal]=useState<'extension'|'hardware'|null>(null);const [readerOnly,setReaderOnly]=useState(extension);const [speaking,setSpeaking]=useState(false);const [all,setAll]=useState(false);const [sourceMode,setSourceMode]=useState<'page'|'dom'>('page');const [changed,setChanged]=useState(false);
 const epoch=useRef(0);const output=useRef<HTMLTextAreaElement>(null);const abort=useRef<AbortController|null>(null);const pageRef=useRef(page);pageRef.current=page;
 useEffect(()=>{fetch(API+'/api/config').then(r=>r.json()).then(v=>setConfigured(v.jevConfigured)).catch(()=>{});return()=>{abort.current?.abort();speechSynthesis?.cancel();};},[]);
 function acceptPage(p:PageSnapshot){epoch.current++;abort.current?.abort();setPage(p);setResult(null);setSelected(p.blocks[0]?.id||'');setOffset(0);setCellOffset(0);setChanged(false);setError('');setStatus(`${p.blocks.length} DOM blocks captured. Ready for Jev.`);}
 useEffect(()=>{if(!extension)return;chrome.storage.session.get(['snapshot','captureError','pageChanged']).then(v=>{if(v.snapshot)acceptPage(v.snapshot as PageSnapshot);if(v.captureError)setError(String(v.captureError));setChanged(!!v.pageChanged);});const listener=(changes:Record<string,chrome.storage.StorageChange>,area:string)=>{if(area!=='session')return;if(changes.snapshot?.newValue)acceptPage(changes.snapshot.newValue as PageSnapshot);if(changes.captureError)setError(String(changes.captureError.newValue||''));if(changes.pageChanged)setChanged(!!changes.pageChanged.newValue);};chrome.storage.onChanged.addListener(listener);return()=>chrome.storage.onChanged.removeListener(listener);},[]);
 async function loadExample(){setBusy('load');setError('');try{const html=await fetch(extension?API+'/example.html':'/example.html').then(r=>r.text());const doc=new DOMParser().parseFromString(html,'text/html');const p=extractDocument(doc,API?API+'/example.html':location.origin+'/example.html');p.source='example';p.previewHtml='<!doctype html>'+doc.documentElement.outerHTML;acceptPage(p);setUrl(p.url);return p;}catch{setError('Could not load the sample website.');return null;}finally{setBusy(null);}}
 async function loadUrl(){const raw=url.trim();setBusy('load');setError('');epoch.current++;abort.current?.abort();const controller=new AbortController();abort.current=controller;const token=epoch.current;try{const response=await fetch(API+'/api/page',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({url:raw.startsWith('http')?raw:'https://'+raw})});const p=await response.json();if(!response.ok)throw new Error(p.error);if(epoch.current!==token)return;acceptPage(p);setUrl(p.url);}catch(e){if(e instanceof Error&&e.name!=='AbortError')setError(e.message);}finally{setBusy(null);}}
 async function rank(target=page){if(!target)return;const token=++epoch.current;abort.current?.abort();const controller=new AbortController();abort.current=controller;setBusy('rank');setError('');setStatus('Jev is scoring relevance and classifying each DOM block…');const goal=task;try{const {previewHtml,...payload}=target;const r=await fetch(API+'/api/rank',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({page:payload,task:goal})});const data=await r.json();if(!r.ok)throw new Error(data.error);if(token!==epoch.current)return;setResult(data);const first=readingOrder(target,data)[0];setSelected(first?.id||'');setOffset(0);setCellOffset(0);setStatus(`Jev classified ${data.results.length} DOM blocks in ${data.latencyMs} milliseconds. Reading order is ready.`);setConfigured(true);}catch(e){if(token!==epoch.current)return;if(e instanceof Error&&e.name!=='AbortError'){setError(e.message);setStatus('Your source text remains available. No AI scores were applied.');}}finally{if(token===epoch.current)setBusy(null);}}
 function updateTask(value:string){epoch.current++;abort.current?.abort();setBusy(null);setTask(value);setResult(null);setStatus('Task changed. Classify again to get a new reading order.');}
 const ordered=page?readingOrder(page,result):[];const current=page?.blocks.find(b=>b.id===selected)||ordered[0];const currentRank=result?.results.find(r=>r.id===current?.id);const selectedIndex=ordered.findIndex(b=>b.id===current?.id);const text=current?.text||'Your selected text will appear here.';const chars=Array.from(text);const line=chars.slice(offset,offset+40).join('');const allDots=toBraille(line);const dots=allDots.slice(cellOffset,cellOffset+cells);const ranks=new Map(result?.results.map(r=>[r.id,r])||[]);const shown=all?ordered:ordered.slice(0,8);
 function readBlock(block:DomBlock){setSelected(block.id);setOffset(0);setCellOffset(0);setStatus(`Reading ${block.role}: ${block.text}`);if(speaking)speak(block.text);}
 function pan(direction:number){setOffset(o=>Math.min(Math.max(0,o+direction*40),Math.max(0,Math.floor((chars.length-1)/40)*40)));setCellOffset(0);}
 function speak(value=text){if(!('speechSynthesis'in window)){setError('This browser does not support speech. The text output works with your screen reader.');return;}speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(value);utterance.lang='en-US';utterance.rate=.95;utterance.onend=()=>setSpeaking(false);utterance.onerror=()=>setSpeaking(false);setSpeaking(true);speechSynthesis.speak(utterance);}
 function stopSpeech(){speechSynthesis.cancel();setSpeaking(false);}
 async function captureTab(){setError('');try{await chrome.runtime.sendMessage({type:'capture'});}catch{setError('Open a web page and click the Brailly extension icon first.');}}
 function exportTrace(){if(!result)return;const blob=new Blob([JSON.stringify({page,result},null,2)],{type:'application/json'});const link=document.createElement('a');const u=URL.createObjectURL(blob);link.href=u;link.download='brailly-dom-classification.json';link.click();URL.revokeObjectURL(u);}
 const preview=page?.previewHtml?.replace('</head>',`<style>[data-brailly-id="${current?.id||''}"]{outline:3px solid #2d5bdb!important;outline-offset:5px!important;background-color:#eaf0ff!important;border-radius:2px}html{overflow-x:hidden!important}body{pointer-events:none!important}</style></head>`);
 return <div className={`brailly ${readerOnly?'reader-only':''} ${extension?'extension-app':''}`}>
 <a className="skip" href="#reading-output">Skip to reading output</a>
 <header className="header"><a className="wordmark" href="/" aria-label="Brailly home"><span className="logo-dots" aria-hidden="true">⠃</span>brailly<span className="demo-tag">WEB → BRAILLE</span></a><nav aria-label="Tools"><button onClick={()=>setReaderOnly(!readerOnly)}><Headphones size={15}/>{readerOnly?'Show walkthrough':'Reader mode'}</button><button aria-label="Get the extension" onClick={()=>setModal('extension')}><PanelRight size={15}/><span>Get the extension</span></button></nav></header>
 <main>
 {!readerOnly&&<section className="intro"><div><span className="eyebrow">LESS SEARCHING. MORE READING.</span><h1>Your web.<br className="mobile-break"/> In reading order.</h1><p>Give Jev a page and a purpose. Get the content that matters,<br className="desktop-break"/> ready for a screen reader or a Braille display.</p></div><div className="process" aria-label="How it works"><span><Globe size={18}/>Web page</span><ArrowRight size={14}/><span className="jev-word">Jev<small>Score + Choice</small></span><ArrowRight size={14}/><span><span className="braille-symbol">⠿⠿</span>Your reader</span></div></section>}
 <section className="input-panel" aria-label="Page and task"><div className="input-line"><label htmlFor="url"><Globe size={16}/><span className="sr-only">Website URL</span></label><input id="url" type="text" placeholder="Paste a website URL…" value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void loadUrl();}} disabled={extension}/>{extension?<button className="load-button" onClick={captureTab}><RefreshCw size={15}/> Capture tab</button>:<button className="load-button" onClick={loadUrl} disabled={busy!==null||!url.trim()}>{busy==='load'?<LoaderCircle className="spin" size={15}/>:<ArrowRight size={16}/>}Load page</button>}</div><div className="task-line"><label htmlFor="goal">I want to</label><input id="goal" value={task} maxLength={500} onChange={e=>updateTask(e.target.value)} placeholder="Find what I need on this page…"/><button className="primary" onClick={()=>void rank()} disabled={!page||busy!==null||task.trim().length<3}>{busy==='rank'?<LoaderCircle className="spin" size={16}/>:<span className="spark">✳</span>}{busy==='rank'?'Jev is classifying…':'Classify with Jev'}</button></div></section>
 <div className="under-input"><div><span>Try a page:</span><button onClick={()=>void loadExample()} disabled={!!busy}>Museum demo <ArrowUpRight size={12}/></button><button onClick={()=>{setUrl('https://docs.typesafe.ai/primitives/score');updateTask('Understand how to use a Score and interpret its result.');}}>Jev documentation <ArrowUpRight size={12}/></button></div><span className={`connection ${result?'connected':''}`}><i/>{result?'Live Jev result':configured?'Jev key configured':'Live Jev needs an API key'}</span></div>
 {error&&<div className="error" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
 {changed&&<div className="warning" role="status">The source page changed. Your reading snapshot is held. Capture the tab again when you are ready.</div>}
 {!readerOnly&&<div className="walkthrough">
 <section className="source-panel"><div className="section-header"><h2><span>1</span>The web page</h2><div className="segmented"><button className={sourceMode==='page'?'active':''} onClick={()=>setSourceMode('page')}>Page</button><button className={sourceMode==='dom'?'active':''} onClick={()=>setSourceMode('dom')}>DOM</button></div></div><div className="browser-frame"><div className="browser-bar"><div className="traffic"><i/><i/><i/></div><span><Globe size={11}/>{page?new URL(page.url).hostname:'Your website'}</span><button aria-label="Open original page" disabled={!page} onClick={()=>page&&window.open(page.url,'_blank','noopener,noreferrer')}><ArrowUpRight size={14}/></button></div>
 {page?(sourceMode==='page'&&preview?<iframe title="Sanitized source page snapshot" sandbox="" srcDoc={preview}/>:<div className="dom-source">{page.blocks.map(b=><button key={b.id} className={b.id===current?.id?'selected':''} onClick={()=>readBlock(b)}><code>&lt;{b.tag}&gt;<small>{b.id} · {b.region}</small></code><span>{b.text}</span></button>)}</div>):<div className="empty-source"><div className="empty-browser"><div/><span/><span/><b/><span/></div><h3>Start with an actual page.</h3><p>Paste a URL, or load the museum demo.<br/>Brailly extracts its headings, links, controls and text.</p><button className="subtle" onClick={()=>void loadExample()}>Load museum demo <ArrowRight size={14}/></button></div>}
 </div><div className="panel-caption"><ShieldCheck size={13}/>{page?.source==='extension'?'Rendered DOM captured from your active tab.':page?.source==='example'?'A sample website. Real DOM extraction; no scripted AI results.':'URL mode captures server HTML. The extension reads rendered pages.'}</div></section>
 <section className="classification-panel"><div className="section-header"><h2><span>2</span>What Jev makes of it</h2><span className="type-pill">Score + Choice</span></div><div className="extension-frame"><div className="extension-top"><span className="mini-brand">⠃ brailly</span><span className="small-label">READING PRIORITY</span><PanelRight size={15}/></div><div className="goal-summary"><small>YOUR PURPOSE</small><p>{task||'Describe what you need from this page.'}</p></div><div className="list-heading"><span>{result?'SORTED BY JEV RELEVANCE':page?'DOM ORDER · NOT YET CLASSIFIED':'YOUR PAGE, ORGANIZED'}</span><span>{page?.blocks.length||0} blocks</span></div>
 <div className="block-list">{shown.length?shown.map((b,index)=>{const r=ranks.get(b.id);return <button key={b.id} className={`block-row ${b.id===current?.id?'selected':''}`} onClick={()=>readBlock(b)}><span className="block-number">{String(index+1).padStart(2,'0')}</span><div><span className="block-meta">{r?<><b className={`priority ${r.priority.toLowerCase()}`}>{priorityLabel[r.priority]}</b><span>{categoryLabel[r.category]}</span></>:<><b>{b.role}</b><span>{b.tag}</span></>}</span><span className="block-copy">{b.text}</span>{r&&<span className="score-bar"><i style={{width:`${r.score/3*100}%`}}/></span>}</div><span className="score-value">{r?<>{r.score.toFixed(1)}<small>/ 3</small></>:<ChevronDown size={12}/>}</span></button>}):<div className="empty-classification"><Layers size={28}/><p>Navigation. Content. Actions.<br/>Jev scores each block for your task.</p><span>Every score will come from a live API call.</span></div>}</div>
 {ordered.length>8&&<button className="show-all" onClick={()=>setAll(!all)}>{all?'Show first 8 blocks':`Show all ${ordered.length} blocks`} <ChevronDown size={13}/></button>}
 <div className="classification-footer"><span className="status-dot"/><span>{result?`${result.model} · ${result.latencyMs} ms`:'All original content stays available.'}</span><button onClick={()=>setShowCode(!showCode)} aria-label="Inspect Jev request and results"><Code2 size={15}/></button></div></div><div className="panel-caption"><MousePointer2 size={13}/>Select any block to feel how the reading order changes.</div></section>
 </div>}
 {readerOnly&&<section className="compact-list"><h2>{page?.title||'Brailly reader'}</h2><p>Choose a block. Scores appear only after a live Jev classification.</p><label htmlFor="block-picker">Reading block</label><select id="block-picker" value={current?.id||''} onChange={e=>{const b=page?.blocks.find(b=>b.id===e.target.value);if(b)readBlock(b);}}>{ordered.map((b,i)=><option key={b.id} value={b.id}>{i+1}. {b.text.slice(0,110)}</option>)}</select></section>}
 <section className="output-section" aria-label="Accessible reading output"><div className="output-heading"><div><h2><span>3</span>One block. Your way to read.</h2><p>The original words, sent to voice, text and the simulated display.</p></div><button className="hardware-link" onClick={()=>setModal('hardware')}>About the hardware <ArrowUpRight size={13}/></button></div><div className="output-layout"><div className="text-output"><div className="output-meta"><span>{current?`${current.id} · ${currentRank?categoryLabel[currentRank.category]:current.role}`:'READING OUTPUT'}</span><span>{page?'Exact source text':'No page loaded'}</span></div><textarea id="reading-output" ref={output} readOnly value={line} rows={3} aria-label="Stable reading output" aria-live="polite" aria-atomic="true"/><div className="reader-buttons"><button onClick={()=>{if(ordered[selectedIndex-1])readBlock(ordered[selectedIndex-1]);}} disabled={selectedIndex<=0} aria-label="Previous block"><ArrowLeft size={15}/></button><span>{current?`${selectedIndex+1} of ${ordered.length}`:'0 blocks'}</span><button onClick={()=>{if(ordered[selectedIndex+1])readBlock(ordered[selectedIndex+1]);}} disabled={selectedIndex>=ordered.length-1} aria-label="Next block"><ArrowRight size={15}/></button><button className="listen" onClick={()=>speaking?stopSpeech():speak()} disabled={!page}>{speaking?<VolumeX size={15}/>:<Volume2 size={15}/>} {speaking?'Stop':'Listen'}</button></div></div>
 <div className="hardware-wrap"><div className="device"><div className="device-top"><span>brailly <b>touch</b></span><span className="simulated-dot"><i/>SIMULATED DISPLAY</span></div><div className="device-middle"><button onClick={()=>cellOffset>0?setCellOffset(Math.max(0,cellOffset-cells)):pan(-1)} aria-label="Pan Braille left"><ArrowLeft size={16}/></button><div className="dot-window" style={{gridTemplateColumns:`repeat(${cells},minmax(0,1fr))`}} aria-hidden="true">{Array.from({length:cells},(_,i)=><span className="cell" key={i}><b/>{[0,3,1,4,2,5].map(bit=><i className={(dots[i]??0)&(1<<bit)?'up':''} key={bit}/>)}</span>)}</div><button onClick={()=>cellOffset+cells<allDots.length?setCellOffset(cellOffset+cells):pan(1)} aria-label="Pan Braille right"><ArrowRight size={16}/></button></div><div className="device-bottom"><span>{cells} CELLS · ENGLISH PREVIEW</span><i/><span>{Math.floor(cellOffset/cells)+1}/{Math.max(1,Math.ceil(allDots.length/cells))}</span></div></div><div className="device-controls"><span>Illustrative dots. Screen readers handle real Braille translation.</span><label><span className="sr-only">Display cells</span><select value={cells} onChange={e=>{setCells(Number(e.target.value));setCellOffset(0);}}><option value={20}>20 cells</option><option value={40}>40 cells</option><option value={80}>80 cells</option></select></label></div></div></div>
 <div className="output-foot"><div><button onClick={()=>pan(-1)} disabled={offset===0}>Previous text line</button><span>{offset+1}–{Math.min(offset+40,chars.length)} / {chars.length} characters</span><button onClick={()=>pan(1)} disabled={offset+40>=chars.length}>Next text line</button></div>{extension&&current&&<button onClick={()=>chrome.runtime.sendMessage({type:'locate',id:current.id,text:current.text})}>Go to original element <ArrowUpRight size={13}/></button>}<button onClick={()=>output.current?.focus()}><Headphones size={13}/> Focus screen reader output</button></div></section>
 <div className="live-status" role="status" aria-live="polite">{status}</div>
 {page?.truncated&&<p className="coverage">Showing the first {page.blocks.length} eligible blocks of {page.totalCandidates}; long text is capped at 800 characters per block. This is a bounded preview, not the full accessibility tree.</p>}
 {showCode&&<section className="code-panel"><div><h2>Under the hood</h2><button className="subtle" disabled={!result} onClick={exportTrace}><Download size={14}/> Export result</button></div><p>One Score (0–3) and one Choice per block. The task and DOM metadata are structured inputs. Confidence is reported separately from relevance.</p><pre>{JSON.stringify(result?{request:result.request,response:{model:result.model,latencyMs:result.latencyMs,results:result.results}}:page?{task,dom:page.blocks}:'Load a page to inspect its extracted DOM.',null,2)}</pre></section>}
 <footer><span>Built for sequential reading.</span><div><a href="https://docs.typesafe.ai/primitives/score" target="_blank" rel="noreferrer">Jev Score <ArrowUpRight size={11}/></a><button onClick={()=>setShowCode(!showCode)}>See how Jev is used <Code2 size={13}/></button></div></footer>
 </main>
 {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setModal(null);if(e.key==='Tab'){const items=e.currentTarget.querySelectorAll<HTMLElement>('a,button');const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><button className="close" autoFocus onClick={()=>setModal(null)} aria-label="Close dialog"><X size={20}/></button><span className="modal-icon">{modal==='extension'?<PanelRight size={25}/>:<AudioLines size={25}/>}</span><h2 id="modal-title">{modal==='extension'?'Bring Brailly to your browser.':'The output is for the reader.'}</h2>{modal==='extension'?<><p>The Chrome extension captures the actual rendered DOM of the tab you choose, then opens Brailly beside it. Classification sends the extracted page text to Jev only when you press the button.</p><ol><li><a href="/brailly-extension.zip" download>Download the extension ZIP</a> and unzip it.</li><li>Open <code>chrome://extensions</code> and turn on Developer mode.</li><li>Choose <b>Load unpacked</b> and select the extracted folder.</li><li>Open a web page and click Brailly. Set your purpose and choose <b>Classify with Jev</b>.</li></ol><p className="note">Active-tab access only. Passwords and input values are excluded. Chrome internal pages, cross-origin frames and closed shadow roots are not captured. The extension is unpacked, not a Chrome Web Store release.</p></>:<><p>The dots explain the output visually for this demo. A blind reader can use keyboard navigation, a screen reader, or the Listen control without seeing the page.</p><h3>With a real Braille display</h3><p>Pair a supported display with VoiceOver or NVDA, then focus “Stable reading output.” The screen reader controls translation, contractions, and device routing.</p><h3>Direct hardware prototype</h3><p>The repository also includes a local BRLTTY bridge. Vercel cannot reach your USB hardware directly. There is no physical display connected to this demo.</p><a href="https://support.apple.com/en-au/guide/voiceover/cpvoubradisplays/mac" target="_blank" rel="noreferrer">VoiceOver Braille setup <ArrowUpRight size={14}/></a><p className="note">The visual dot mapping is illustrative English, not certified Braille translation. Physical device and Braille-reader validation are still pending.</p></>}</section></div>}
 </div>;
}
