import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight, ArrowRight, ArrowLeft, Play, RotateCcw, Pause, Plane, ShieldCheck, Radio, ChevronDown, ChevronRight, Activity, SlidersHorizontal, Usb, Check, X, Download, Sun, Moon, Headphones, CircleDot} from 'lucide-react';
import {initialState,reducer,visibleText,isHistorical,capture,fixtureDecision,taskText,SECURITY_NOTICE,type Action,type Update,type BlockId,type Verdict,type Policy} from './runtime';
import {toBraille} from './braille';
type Status={jev:boolean;model:string;hardware:{connected:boolean;message:string;columns?:number;driver?:string}};
const labels:Record<string,string>={DEFER:'Deferred',QUEUE_HIGH:'Queued',INTERRUPT:'Interrupt',NONE:'Review needed'};
export default function App(){
 const [s,setS]=useState(initialState);const ref=useRef(s);const [status,setStatus]=useState<Status>({jev:false,model:'',hardware:{connected:false,message:'No device connected'}});
 const [panel,setPanel]=useState<'queue'|'trace'>('trace');const [hardwareOpen,setHardwareOpen]=useState(false);const [settings,setSettings]=useState(false);const [custom,setCustom]=useState('');const [entity,setEntity]=useState<BlockId>('security');const [running,setRunning]=useState(false);const runId=useRef(0);const [evaluating,setEvaluating]=useState(false);const evaluatingRef=useRef(false);const [theme,setTheme]=useState('light');const [cells,setCells]=useState(40);const [braillePositions,setBraillePositions]=useState<Record<string,number>>({});const [slow,setSlow]=useState(false);const [forcedTimeout,setForcedTimeout]=useState(false);const [readerMode,setReaderMode]=useState(false);const readerRef=useRef<HTMLTextAreaElement>(null);
 function dispatch(a:Action){ref.current=reducer(ref.current,a);setS(ref.current);}
 async function refreshStatus(){try{const r=await fetch('/api/status');if(r.ok)setStatus(await r.json());}catch{/* server status remains unconfirmed */}}
 useEffect(()=>{void refreshStatus();const timer=setInterval(refreshStatus,2500);return()=>clearInterval(timer);},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;},[theme]);
 const brailleKey=`${s.active?.id??`v${s.snapshot.version}-${s.snapshot.blockId}`}:${s.active?s.noticeOffset:s.snapshot.offset}:${cells}`;const braillePage=braillePositions[brailleKey]??0;const setBraillePage=(value:number)=>setBraillePositions(previous=>({...previous,[brailleKey]:value}));
 const line=visibleText(s);const dots=toBraille(line);const maxBraillePage=Math.max(0,Math.ceil(dots.length/cells)-1);const page=Math.min(braillePage,maxBraillePage);const braille=dots.slice(page*cells,(page+1)*cells);const pending=s.events.filter(e=>e.status!=='published');const history=isHistorical(s);
 useEffect(()=>{if(status.hardware.connected){fetch('/api/hardware/write',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:line})}).then(r=>{if(!r.ok)void refreshStatus();}).catch(()=>void refreshStatus());}},[line,status.hardware.connected]);
 async function emit(kind:Update['kind'],text?:string,block?:BlockId){
  const blockId=block??(kind==='noise'?'weather':kind==='gate'?'gate':kind==='baggage'?'baggage':'security');
  const event:Update={id:crypto.randomUUID(),blockId,revision:ref.current.blocks[blockId].revision+1,at:Date.now(),kind,status:'pending',text:text??(kind==='noise'?`San Francisco · ${69+ref.current.updates%5}°F · Clear skies.`:kind==='gate'?`Flight UA 245 · Gate ${ref.current.blocks.gate.text.includes('F22')?'F18':'F22'} · Boarding at 14:20 · San Francisco to New York.`:kind==='baggage'?'Baggage information · carousel 7 · Keep your baggage receipt until the end of your journey.':SECURITY_NOTICE)};
  dispatch({type:'update',event});const key=capture(ref.current,event);const capturedTask=taskText(ref.current.task);const capturedGate=structuredClone(ref.current.blocks.gate);let verdict=fixtureDecision(event,ref.current.task);const start=performance.now();
  if(kind==='notice'&&ref.current.policy==='Braily'){
   if(evaluatingRef.current)verdict={disposition:'NONE',source:'Fallback',latencyMs:0,reason:'Another evaluation is active. This event is retained for review.'};
   else {evaluatingRef.current=true;setEvaluating(true);try{
    if(slow)await new Promise(r=>setTimeout(r,1800));
    if(forcedTimeout)throw new Error('Simulated timeout; event retained for review.');
    if(status.jev){const r=await fetch('/api/classify',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(3500),body:JSON.stringify({task:capturedTask,snapshot:key.snapshot,event:{text:event.text,blockId:event.blockId,revision:event.revision},context:{gate:capturedGate}})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Jev unavailable');verdict=data;}
   }catch(error){verdict={disposition:'NONE',source:'Fallback',latencyMs:Math.round(performance.now()-start),reason:error instanceof Error?error.message:'Connection failed; retained for review.'};}finally{evaluatingRef.current=false;setEvaluating(false);}}
  }else if(ref.current.policy!=='Braily')verdict={disposition:ref.current.policy==='Immediate'?'INTERRUPT':'DEFER',source:'Rule',latencyMs:0,reason:`${ref.current.policy}: controlled comparison policy.`};
  dispatch({type:'decision',key,verdict});
 }
 const emitRef=useRef(emit);emitRef.current=emit;
 function stop(){runId.current++;setRunning(false);dispatch({type:'phase',value:'Demo paused · explore at your own pace'});}
 async function runDemo(){
  const id=++runId.current;dispatch({type:'reset'});setRunning(true);setPanel('trace');
  const wait=async(ms:number)=>{await new Promise(r=>setTimeout(r,ms));return runId.current===id;};
  dispatch({type:'phase',value:'01 / A quiet place to read'});if(!await wait(1600))return;
  dispatch({type:'phase',value:'02 / The world keeps updating'});
  for(let i=0;i<6;i++){if(runId.current!==id)return;await emitRef.current('noise');if(!await wait(500))return;}
  dispatch({type:'phase',value:'03 / One update changes your route'});await emitRef.current('notice');if(!await wait(4000))return;
  if(ref.current.active){dispatch({type:'phase',value:'04 / Return to exactly where you were'});dispatch({type:'resume'});}else dispatch({type:'phase',value:'04 / Review the decision and any pending notice'});
  if(!await wait(1800))return;
  dispatch({type:'phase',value:'05 / Same notice. A different task.'});dispatch({type:'task',value:'after'});await emitRef.current('notice');if(runId.current!==id)return;
  dispatch({type:'phase',value:'Demo complete · try your own update below'});setRunning(false);
 }
 useEffect(()=>()=>{runId.current++;},[]);
 function download(){const blob=new Blob([JSON.stringify({recordedAt:new Date().toISOString(),simulation:true,policy:s.policy,task:taskText(s.task),events:s.events,traces:s.traces,metrics:{updates:s.updates,interruptions:s.interruptions,rewrites:s.rewrites,stale:s.stale,resumes:s.resumes}},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='braily-demo-trace.json';a.click();URL.revokeObjectURL(url);}
 const latencies=s.traces.filter(t=>t.source==='Jev').map(t=>t.latencyMs).sort((a,b)=>a-b);const p95=latencies.length?latencies[Math.ceil(latencies.length*.95)-1]:null;
 return <div className="app-shell">
 <a className="skip-link" href="#reader">Skip to reading output</a>
 <header className="topbar"><a className="brand" href="/" aria-label="Braily home"><span className="brandmark"><i/><i/><i/></span>braily<span className="beta">LAB</span></a><nav aria-label="Main"><a className="nav-active" href="#workspace">Live demo</a><button onClick={()=>setHardwareOpen(true)}>Hardware <ArrowUpRight size={13}/></button><a href="https://docs.typesafe.ai" target="_blank" rel="noreferrer">Built with Jev <ArrowUpRight size={13}/></a></nav><div className="top-right"><span className="event-label">JEVATHON ’26</span><button className="icon-button" aria-label="Toggle color theme" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={17}/>:<Sun size={17}/>}</button></div></header>
 <main id="workspace">
 <section className="intro"><div><div className="eyebrow"><span className="dot"/> ACCESSIBILITY, AT YOUR PACE</div><h1>The world moves.<br/>Your place stays.</h1><p>A quieter way to read a changing world. Braily holds your place<br className="desktop-break"/> and brings forward only the updates that matter to your task.</p></div><div className="intro-action"><button className="primary run" onClick={running?stop:runDemo}>{running?<Pause size={17}/>:<Play size={17} fill="currentColor"/>}{running?'Pause demo':'Play the demo'}<span>{running?'Running':'~15 sec'}</span></button><p><span className="dot muted"/>{status.jev?'Live Jev connected':'Offline fixture demo'} · no device needed</p></div></section>
 <section className="workspace-toolbar" aria-label="Demo controls"><div className="toolbar-title"><Radio size={16}/><span>Interactive workspace</span><span className="tiny-label">SIMULATION</span></div><div className="policy-controls" aria-label="Publication policy">{(['Immediate','Freeze','Braily'] as Policy[]).map(p=><button aria-pressed={s.policy===p} className={s.policy===p?'selected':''} onClick={()=>{if(running)stop();dispatch({type:'policy',value:p});}} key={p}>{p==='Braily'&&<span className="little-dot"/>}{p}</button>)}</div><button className="icon-button" aria-label="Reset demo" onClick={()=>{stop();dispatch({type:'reset'});}}><RotateCcw size={17}/></button></section>
 <div className="workspace-grid">
 <section className="flight-panel panel" aria-labelledby="flight-title"><div className="section-caption"><span>01 / THE LIVE WORLD</span><span className="live-indicator"><span className="dot"/>LIVE</span></div><div className="flight-title"><span className="plane-badge"><Plane size={21}/></span><div><h2 id="flight-title">Your next departure</h2><p>United Airlines · UA 245</p></div><span className="flight-date">26 SEP</span></div>
 <div className="route"><div><strong>SFO</strong><span>San Francisco</span></div><div className="route-line"><span/><Plane size={19}/><span/></div><div><strong>JFK</strong><span>New York</span></div></div>
 <div className="flight-details"><div><span>GATE</span><strong>{s.blocks.gate.text.includes('F22')?'F22':'F18'}</strong></div><div><span>BOARDING</span><strong>14:20</strong></div><div><span>STATUS</span><strong className="on-time">On time</strong></div></div>
 <div className="task-box"><label htmlFor="task"><CircleDot size={15}/> THE READER’S TASK</label><select id="task" value={s.task} onChange={e=>{if(running)stop();dispatch({type:'task',value:e.target.value as 'before'|'after'});}}><option value="before">Reach F18 · before security</option><option value="after">Wait at F18 · after security</option></select><p>{s.task==='before'?'I’m before security, planning to use checkpoint A.':'I’ve passed security and I’m already at the gate.'}</p></div>
 <div className="app-facts"><div><span><Sun size={15}/> Local weather</span><b>{s.blocks.weather.text.match(/\d+°F/)?.[0]}</b></div><div><span><Headphones size={15}/> Baggage carousel</span><b>{s.blocks.baggage.text.includes('carousel 7')?'07':'04'}</b></div></div>
 <div className="trigger-section"><div className="small-heading">SEND AN UPDATE <span>Try it live</span></div><button className="trigger" onClick={()=>void emit('noise')}><span className="trigger-icon neutral"><Activity size={16}/></span><span><b>Everyday noise</b><small>Weather changes. Your place stays.</small></span><ChevronRight size={17}/></button><button className="trigger" onClick={()=>void emit('notice')}><span className="trigger-icon amber"><ShieldCheck size={16}/></span><span><b>Security notice</b><small>A change that could alter your route.</small></span><ChevronRight size={17}/></button><button className="trigger" onClick={()=>void emit('gate')}><span className="trigger-icon green"><Plane size={16}/></span><span><b>Gate change</b><small>A known change, handled by a rule.</small></span><ChevronRight size={17}/></button></div>
 <div className="source-footer"><span className="dot"/> Source revision <b>v{s.version}</b><span>Always updating</span></div>
 </section>
 <section className="reader-panel panel" aria-labelledby="reader-title"><div className="section-caption"><span>02 / THE READER’S SPACE</span><button className="text-button" onClick={()=>setSettings(!settings)} aria-expanded={settings}><SlidersHorizontal size={14}/> Settings</button></div><div className="reader-heading"><div><h2 id="reader-title">A little room to read.</h2><p>Everything else can wait a moment.</p></div><span className={`lease-badge ${s.active?'alert':''}`}><span className="dot"/>{s.active?'Interrupted':history?'Historical snapshot':'ReadLease active'}</span></div>
 {settings&&<div className="settings"><label>Display size<select value={cells} onChange={e=>setCells(Number(e.target.value))}><option value={20}>20 cells</option><option value={40}>40 cells</option><option value={80}>80 cells</option></select></label><label><input type="checkbox" checked={slow} onChange={e=>setSlow(e.target.checked)}/> Delay decision 1.8s (change task to test stale results)</label><label><input type="checkbox" checked={forcedTimeout} onChange={e=>setForcedTimeout(e.target.checked)}/> Simulate a service timeout</label><button onClick={()=>void emit('baggage')}>Change the retained baggage text</button></div>}
 <div className="reading-select"><span>READING</span><select aria-label="Reading block" value={s.snapshot.blockId} onChange={e=>dispatch({type:'block',id:e.target.value as BlockId})}>{Object.values(s.blocks).map(b=><option key={b.id} value={b.id}>{b.label}</option>)}</select><span>v{s.snapshot.version}</span></div>
 <div className={`reading-output ${s.active?'interrupted':''}`}><div className="output-label"><span>{s.active?'AN UPDATE FOR YOUR TASK':'YOUR CURRENT LINE'}</span><span>{s.active?`notice v${s.active.revision}`:`${s.snapshot.offset+1}–${s.snapshot.offset+Array.from(line).length}`}</span></div><textarea id="reader" ref={readerRef} readOnly aria-label="Stable reading output" aria-live={readerMode?'polite':'off'} aria-atomic="true" value={line} rows={2} spellCheck={false}/><div className="output-foot"><span>{s.active?<><span className="dot amber-dot"/> Source text · never rewritten by AI</>:<><ShieldCheck size={13}/> Your reading position is held</>}</span><span>40 text characters</span></div></div>
 <div className="device" aria-label={`Simulated ${cells}-cell Braille display`}><div className="device-top"><span className="device-brand">braily <b>touch</b></span><span className="device-status"><span/>SIMULATED DEVICE</span></div><div className="device-body"><button aria-label="Pan Braille display left" className="device-pan" onClick={()=>page>0?setBraillePage(page-1):dispatch({type:'pan',direction:-1,width:40})}><ArrowLeft size={16}/></button><div className="braille-window" style={{gridTemplateColumns:`repeat(${cells}, minmax(0, 1fr))`}} aria-hidden="true">{Array.from({length:cells},(_,i)=><div className="braille-cell" key={i}><div className="routing-dot"/>{[0,3,1,4,2,5].map(bit=><i key={bit} className={(braille[i]??0)&(1<<bit)?'raised':''}/>)}</div>)}</div><button aria-label="Pan Braille display right" className="device-pan" onClick={()=>page<maxBraillePage?setBraillePage(page+1):dispatch({type:'pan',direction:1,width:40})}><ArrowRight size={16}/></button></div><div className="device-bottom"><span>{cells} CELLS · ENGLISH DOT PREVIEW</span><span className="device-space"/><span data-testid="braille-page">{page+1} / {maxBraillePage+1}</span></div></div>
 <div className="device-note">Illustrative uncontracted English · a visual simulation, not tactile validation.</div>
 <div className="reader-controls"><div><button aria-label="Previous text line" onClick={()=>dispatch({type:'pan',direction:-1,width:40})}><ArrowLeft size={16}/></button><button aria-label="Next text line" onClick={()=>dispatch({type:'pan',direction:1,width:40})}><ArrowRight size={16}/></button><span>Pan text</span></div>{s.active?<button className="primary resume" onClick={()=>dispatch({type:'resume'})}><RotateCcw size={15}/> Resume reading</button>:<button className="subtle" onClick={()=>dispatch({type:'current'})}>Go to current state <ArrowUpRight size={14}/></button>}</div>
 {history&&!s.active&&<p className="historical" role="status">This retained block has changed. You are reading its historical version. Choose “Go to current state” for the latest text.</p>}
 <div className="continuity"><div className="continuity-icon">{s.active?<Radio size={20}/>:<ShieldCheck size={20}/>}</div><div><b>{evaluating?'Evaluating the incoming notice…':s.active?'Something deserves your attention.':s.resumes?'Right back where you left off.':'Your place is protected.'}</b><p>{s.active?'Read the update, then return to the exact saved line.':s.policy==='Braily'?'Updates stay available without taking over this line.':`${s.policy} is an artificial comparison policy.`}</p></div></div>
 <div className="reader-bottom"><span><span className="dot"/>{s.phase}</span><button className="text-button" onClick={()=>{setReaderMode(!readerMode);if(!readerMode)setTimeout(()=>readerRef.current?.focus(),0);}}>{readerMode?'Reader output on':'Screen reader output'} <ArrowUpRight size={13}/></button></div>
 </section></div>
 <section className="observability"><div className="metrics"><div className="metric"><span>Source updates</span><strong>{String(s.updates).padStart(2,'0')}</strong><small>The world kept moving</small></div><div className="metric"><span>Deferred updates</span><strong>{String(s.events.filter(e=>e.status==='deferred').length).padStart(2,'0')}</strong><small>Available in your queue</small></div><div className="metric"><span>Interruptions</span><strong>{String(s.interruptions).padStart(2,'0')}</strong><small>Published to the reading line</small></div><div className="metric"><span>Exact returns</span><strong>{s.resumes?`${s.exactResumes}/${s.resumes}`:'—'}</strong><small>{s.resumes?'Saved block & offset restored':'Run the demo to measure'}</small></div><div className="metric"><span>Live Jev p95</span><strong>{p95===null?'—':<>{p95}<em>ms</em></>}</strong><small>{p95===null?'No live model calls yet':`${latencies.length} measured calls`}</small></div></div>
 <div className="event-panel"><div className="event-header"><div className="tabs"><button className={panel==='trace'?'active':''} onClick={()=>setPanel('trace')}>Decision trail <span>{s.traces.length}</span></button><button className={panel==='queue'?'active':''} onClick={()=>setPanel('queue')}>Pending updates <span>{pending.length}</span></button></div><button className="text-button" onClick={download}><Download size={14}/> Export trace</button></div><div className="trace-content">{panel==='trace'?(s.traces.length?s.traces.map(t=><div className="trace-row" key={t.id}><span className="trace-time">{new Date(t.at).toLocaleTimeString('en-US',{hour12:false})}</span><span className={`decision ${t.stale?'stale':t.disposition.toLowerCase()}`}>{t.stale?'Stale · dropped':labels[t.disposition]}</span><div className="trace-text"><b>{t.text}</b><small>{t.reason}{t.confidence!==undefined&&` · Confidence ${(t.confidence*100).toFixed(1)}%`}{t.probabilities&&` · ${Object.entries(t.probabilities).map(([k,v])=>`${k} ${(v*100).toFixed(1)}%`).join(' / ')}`}</small></div><span className="source-tag">{t.source}{t.source==='Jev'&&` · ${t.latencyMs} ms`}</span></div>):<div className="empty-trace"><Activity size={19}/><span>A clear trail for every decision.<small>Play the demo or send an update to see what happens, and why.</small></span></div>):(pending.length?pending.map(e=><div className="trace-row queue-row" key={e.id}><span className="source-tag">v{e.revision} · {e.status}</span><span className="trace-text">{e.text}</span><button className="subtle" onClick={()=>dispatch({type:'review',id:e.id})}>Read update <ArrowRight size={13}/></button></div>):<div className="empty-trace"><Check size={19}/>Nothing waiting. Every incoming update remains traceable.</div>)}</div></div>
 <form className="custom-form" onSubmit={e=>{e.preventDefault();if(custom.trim()){void emit('notice',custom.trim(),entity);setCustom('');}}}><div><b>Put it to the test.</b><span>Write an update the demo hasn’t seen.</span></div><label className="sr-only" htmlFor="custom">Custom incoming update</label><input id="custom" placeholder="e.g. Checkpoint B closes in 3 minutes…" value={custom} maxLength={2000} onChange={e=>setCustom(e.target.value)}/><select aria-label="Affected entity" value={entity} onChange={e=>setEntity(e.target.value as BlockId)}><option value="security">Security</option><option value="gate">Gate</option><option value="baggage">Baggage</option><option value="weather">Weather</option></select><button type="submit" disabled={!custom.trim()} aria-label="Send custom update"><ArrowRight size={19}/></button></form>
 <p className="mode-note">{status.jev?'Live Jev classifies open notices. Known events use rules.':'Fixture mode: only the prepared notice has a scripted decision. Custom notices are kept for review until a Jev key is configured.'} {s.stale>0&&`${s.stale} stale response(s) discarded; events kept for review.`}</p>
 </section>
 <footer><a className="brand small" href="#">braily</a><span>The web is asynchronous. Reading is personal.</span><button className="text-button" onClick={()=>setHardwareOpen(true)}>From simulation to real Braille <ArrowUpRight size={14}/></button></footer>
 </main>
 {hardwareOpen&&<div className="modal-backdrop" onClick={()=>setHardwareOpen(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="hardware-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setHardwareOpen(false);if(e.key==='Tab'){const nodes=e.currentTarget.querySelectorAll<HTMLElement>('button,a,input,select,textarea');const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><button autoFocus className="close icon-button" aria-label="Close hardware setup" onClick={()=>setHardwareOpen(false)}><X size={20}/></button><span className="eyebrow"><Usb size={16}/> OUTPUT CONNECTIONS</span><h2 id="hardware-title">A real path to touch.</h2><p>The on-screen device is simulated. A physical display is optional for this demo.</p><div className="connection-option"><span className="step">01</span><div><h3>Screen reader → Braille display</h3><p>Pair a supported display with VoiceOver on Mac or NVDA on Windows. Enable “Screen reader output” and move the reader cursor to the stable text field. Your screen reader handles translation and device drivers.</p><a href="https://support.apple.com/guide/voiceover/use-braille-displays-vo15605/mac" target="_blank" rel="noreferrer">VoiceOver setup <ArrowUpRight size={13}/></a><small>Browser APIs cannot confirm the display’s physical connection. Behavior needs testing on the actual device.</small></div></div><div className="connection-option"><span className="step">02</span><div><h3>Direct local BRLTTY adapter</h3><p>On a configured Linux machine, the local Python bridge sends the scheduled text to BRLTTY. BRLTTY handles device drivers and computer Braille translation.</p><div className="hardware-state"><span className={`dot ${status.hardware.connected?'':'muted'}`}/>{status.hardware.message}</div><button className="subtle" onClick={async()=>{await fetch(status.hardware.connected?'/api/hardware/disconnect':'/api/hardware/connect',{method:'POST'});await refreshStatus();}}>{status.hardware.connected?'Disconnect display':'Try local BRLTTY connection'} <Usb size={14}/></button><small>Adapter implemented; physical device testing is still pending.</small></div></div><div className="modal-note">No hardware available? The simulator supports 20, 40, and 80 cells, dot changes, and panning. It does not validate tactile reading or a production Braille translation table.</div></section></div>}
 </div>;
}
